### ISSUE TITLE
JAR -> Q3 -> bugs / remarques

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_ReponseEtudiant_Q3#13]
Voir retour vidéo pour commentaire audio/vidéo [retourvidéo](https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/tree/main/retourVid%C3%A9o)

- [x] => appel de fonction => librairie associée ? 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/e743ee09803b121749fad6c3c083d6b80007cd49/Te_Q3_Jar#L9
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/e743ee09803b121749fad6c3c083d6b80007cd49/Te_Q3_Jar#LL13C35-L13C35
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/e743ee09803b121749fad6c3c083d6b80007cd49/Te_Q3_Jar#L16
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/e743ee09803b121749fad6c3c083d6b80007cd49/Te_Q3_Jar#LL21C4-L21C4
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/e743ee09803b121749fad6c3c083d6b80007cd49/Te_Q3_Jar#L22
- [x] => lecture position tableau => connaître la fin d'un tableau sans la hardcodé 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/e743ee09803b121749fad6c3c083d6b80007cd49/Te_Q3_Jar#LL14C2-L14C28
voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/13#issuecomment-1545287521
- [ ]

**Comment by JeremyETMLES** [comment]
Ajout appel des fonctions: string.h pour les quatres fonctions par rapport aux strigues et stdint.h pour les types normalisé.
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/18d7986da9325ebe0d6c66da15df2ed6b4fc6478/Te_Q3_Jar#LL1C1-L2C20

**Comment by JeremyETMLES** [comment]
Correction de l'hardcodage.
        tbMSGComplet[strlen(pt_message) + 1] = version;
        tbMSGComplet[strlen(pt_message) + 2] = ' ';
        for (i = 0; i < strlen(tbMSG); i++)
        {
                tbMSGComplet[strlen(pt_message) + 2 + i] = tbMSG[i];
        }
        tbMSGComplet[strlen(pt_message)+ 2 + strlen(tbMSG)] = '\0';

**Comment by PBYetml** [comment]
Concernant le point 1 et votre réponse https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/13#issuecomment-1545284995

si vous regarder cet appel de fct : 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/18d7986da9325ebe0d6c66da15df2ed6b4fc6478/Te_Q3_Jar#L24

est-ce que les deux librairies que vous proposez sont-elles suffisantes ? 

point 2 :  
OKI -> pour le hard codage  

nouveau point 3 : 
avez-vous testez cette boucle ? 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/18d7986da9325ebe0d6c66da15df2ed6b4fc6478/Te_Q3_Jar#LL19C1-L22C3

quelle est le nombre d'itération que vous obtenez au total ?! Suis pas sur qu'avec ceci vous obteniez l'information voulue ? qu'a besoin la fct **`strelen`** pour fonctionner correctement ?

**Comment by JeremyETMLES** [comment]
J'ai ajouté la librairie pour itoa (stdlib.h):
       #include <stdlib.h>
et changé la lecture de la taille de tbMSG par sizeof ca il n'y a pas de '\0'
        for (i = 0; i < sizeof(tbMSG); i++)
        ...
        tbMSGComplet[strlen(pt_message)+ 2 + sizeof(tbMSG)] = '\0';

**Comment by PBYetml** [comment]
OKi -> issue fermée !!!
