### ISSUE TITLE
KAN -> Q3 -> bugs / remarques

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_ReponseEtudiant_Q3#3]
Voir retour vidéo pour commentaire audio/vidéo [retourvidéo](https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/tree/main/retourVid%C3%A9o)

- [x] => appel de fct : itoa => utilisation ? 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/fdce05553d11265ed7fbf9469be539a17c51f408/TEST3%20SLO2023_ALLEMANN/Source.c#LL19C1-L19C25
voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/3#issuecomment-1542822056
- [x] => algorithme => gestion des appels des fcts => 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/fdce05553d11265ed7fbf9469be539a17c51f408/TEST3%20SLO2023_ALLEMANN/Source.c#LL16C1-L21C35
=> voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/3#issuecomment-1547713731

**Comment by Kevin-AllemannETML-ES** [comment]
pour demo -> correction de la ligne https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/cd8690de98c389b5f220a536e03846fe1e64b2da/TEST3%20SLO2023_ALLEMANN/Source.c#L19

**Comment by PBYetml** [comment]
Pas de référence sur vos nouvelles implémentations

**Comment by Kevin-AllemannETML-ES** [comment]
1.Le fonction itao sert à convertir un type int en type string, je l'ai stocké dans une variable de type char de grandeur 5,
utilisé pour la conversion de l'année 2022 en string 
ici: https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/e743ee09803b121749fad6c3c083d6b80007cd49/TEST3%20SLO2023_ALLEMANN/Source.c#L31

2. Dans l'ordre copier (strcmpy) TEST dans le tableau msg complet
Ajouté à la case 4 de ce tableau, la version
Ajouté à la case 5 de ce tableau un espace
Ajouté chaque lettre SLO en écriture décimal à l'emplacement voulu dans le tableau
Convertir (itoa) le int dans une variable string pour ensuite le copier "strcmpy" dans le tableau

**Comment by PBYetml** [comment]
2. dans votre solution 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/401fa563f58e0bb2f34c3774b33319e8fa59af64/TEST3%20SLO2023_ALLEMANN/Source.c#LL23C1-L29C29

vous "hardcodez" les positions de votre tableau finale, avez-vous une autre solution, pour ne pas pas hardcoder les position pour la version, l'espace 
même type de question pour la lecture du tableau contenant les 3 caractères -> comment pouvez-vous lire celui-ci sans devoir hardcoder les positions de celui-ci ? 

=> voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/3#issuecomment-1547713731

3. new 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/401fa563f58e0bb2f34c3774b33319e8fa59af64/TEST3%20SLO2023_ALLEMANN/Source.c#L32
pensez-vous que cette ligne peut fonctionner ? comment fonctionne la fct **`strcat`** ?!?
=> voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/3#issuecomment-1547713731

**Comment by Kevin-AllemannETML-ES** [comment]
2. Voici une solution qui ne comprend pas de "hardcoding", pour ce faire j'ai attribué l'espace par la fonction 'strcat' l.25
Autrement il y a une magnifique fonction nommé 'strncat' pemettant d'observer le nombre d'élément à copier mais aussi de convertir l'hexa.
https://github.com/Kevin-AllemannETML-ES/PROG_ReponseEtudiant_Q3/blob/b7a8f5bc83a31bd967cdb307495db8b7a0449cf5/TEST3%20SLO2023_ALLEMANN/Source.c#LL24C1-L28C61

3. Alors chez moi elle fonctionne mais il faudrait lui attribué la chaine pointée. 
char *strcat(char *dest, const char *src) Il permet d'ajouter la chaîne pointée par src à la fin de la chaîne pointée par dest.

https://github.com/Kevin-AllemannETML-ES/PROG_ReponseEtudiant_Q3/blob/b7a8f5bc83a31bd967cdb307495db8b7a0449cf5/TEST3%20SLO2023_ALLEMANN/Source.c#L31

**Comment by PBYetml** [comment]
OKI -> issue fermée !!
