### ISSUE TITLE
MPT -> Q3 -> bugs / remarques 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_ReponseEtudiant_Q3#5]
Voir retour vidéo pour commentaire audio/vidéo [retourvidéo](https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/tree/main/retourVid%C3%A9o)

- [x] => implémentation de base => non implémentée => voir la donnée du CDC 
=> voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/5#issuecomment-1544746043
- [x] => appel fct stcpy => utilisation ? 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/fdce05553d11265ed7fbf9469be539a17c51f408/Test%20programmation_PERRET/Question%203_TE_PROG_24_avril/question_3_TE/question_2.c#LL17C1-L17C70
=> voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/5#issuecomment-1544746043
- [x] => appel fct srtcat => utilisation ? 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/fdce05553d11265ed7fbf9469be539a17c51f408/Test%20programmation_PERRET/Question%203_TE_PROG_24_avril/question_3_TE/question_2.c#LL18C1-L18C58
=> voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/5#issuecomment-1544746043
- [x] => appel fct strlen => utilisation ? 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/fdce05553d11265ed7fbf9469be539a17c51f408/Test%20programmation_PERRET/Question%203_TE_PROG_24_avril/question_3_TE/question_2.c#LL19C1-L19C68
=> voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/5#issuecomment-1544746043
- [x] => appel fct itoa => utilisation ? 
https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/blob/fdce05553d11265ed7fbf9469be539a17c51f408/Test%20programmation_PERRET/Question%203_TE_PROG_24_avril/question_3_TE/question_2.c#LL20C1-L20C46
=> voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/5#issuecomment-1544746043
=> algorithme => utilisation des appels de fonction => voir la donnée du CDC 
=> voir réponse : https://github.com/PBYetml/PROG_ReponseEtudiant_Q3/issues/5#issuecomment-1544746043

**Comment by Melissaperret** [comment]
1) strcpy = permet de copier le contenu d'une chaine de caractère dans une autre. 

2) strcat  = Permet de rajouter à une chaine de caractère déjà existante le contenu 
d'une seconde. 

3) strlen  = Permet de calculer la longueur, exprimée en caractère 

4) itoa =  La fonction convertit le nombre d'entrée en sa string C correspondante en utilisant la base spécifiée.

De plus, j'avais ajouté la librairie : stdio.h afin de pouvoir utiliser la fonction "printf" 
pour utiliser le "int8_t" j'ai dû rajouter la librairie "stdint.h" 

Voici comment j'aurai dû faire mon code : 

#include <stdio.h>
#include <string.h>   //pour strcpy, strcat et strlen 
#include <stdlib.h>   //pour itoa 
#include <stdint.h>   //pour les librairies int8_t



//-- déclaration de constantes --// 
#define TITRE	"TEST"


void main()
{
	const char* pt_message = TITRE;
	const char tbMSG[] = { 0x53, 0x4C, 0x4F };   //Affichage SLO 
	char tbMSGComplet[15];
	int annee = 2023;
	int8_t version = 0x33;  //Affichage 3 

	strcpy(tbMSGComplet, pt_message);
	strncat(tbMSGComplet, &version, 1);
	strcat(tbMSGComplet, " ");
	strncat(tbMSGComplet, tbMSG, sizeof(tbMSG) / sizeof(char)); 
	itoa(annee, &tbMSGComplet[strlen(tbMSGComplet)], 10);
	printf("%s", tbMSGComplet);
	
Le printf me permet de vérifier mon programme et j'ai pu constater qu'il 
 affiche correctement " TEST3 SLO2023" 
	
J'ai utilisé également " strncat*, car avec strcat tout court, la valeur assigné à la variable "version" ne se terminait pas par '\0' qui signifie une fin de chaine de caractère. J'ai donc trouvé cette solution. 
     
 J'ai égalemen rendu le code robuste de façon à si nous ajoutons une case dans "tbMSG" celui-ci recalcul automatiquement le nombre de case et permet d'afficher un nouveau caractère sans avoir un signe étange ou autres.  (voir ligne 37). 
       
PS : mon code contient énormément de commentaire, cela me permettra de povoir le relire dans 1 mois et recomprendre ce que j'ai fait.

**Comment by PBYetml** [comment]
Top => bravo pour la solution avec **`strncat`** 

Issue -> fermée !!!
